name: Run Build

on:
  workflow_dispatch:
    inputs:
      project_name:
        description: Name of the project/application build
        required: true
        default: Test App

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./cli

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      # CLI call to simulated build process
      - name: Run Build
        run: |
          project_name="${{github.event.inputs.project_name}}"
          bash ./build.sh --platform Android --project-name "$project_name"

      # CLI call to simulated upload process
      - name: Upload
        env:
          UPLOAD_TOKEN: dummy-token-credentials
        run: |
          find build/Android -type f | while read -r artifact
          do
            bash ./upload.sh android "$artifact"
          done