name: Run Build

on:
  workflow_dispatch:
    inputs:
      project_name:
        description: Name of project/app build
        required: true
        default: Test App
      project_version_base:
        description: Base project/app version number
        required: true
        default: "1.0"
  push:
    branches:
      - main # the production branch

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./cli

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Prepare build metadata
      - name: Set Build Metadata
        id: meta
        run: |
          if [[ "${{github.event_name}}" == "workflow_dispatch" ]]
          then
            project_name="${{inputs.project_name}}"
            project_version_base="${{inputs.project_version_base}}"
          else
            project_name="Build_${{github.ref_name}}_Branch"
            project_version_base="1.0"
          fi

          project_version="${project_version_base}.${{github.run_number}}"

          echo "project_name=$project_name" >> "$GITHUB_OUTPUT"
          echo "project_version=$project_version" >> "$GITHUB_OUTPUT"
        
      # CLI call to simulated build process
      - name: Run Build
        run: |
          project_name="${{github.event.inputs.project_name}}"
          bash ./build.sh \
            --platform Android \
            --project-name "${{steps.meta.outputs.project_name}}" \
            --version "${{steps.meta.outputs.project_version}}"

      # Upload Build Artifacts for Development
      - name: Upload Build Artifact for Development
        uses: actions/upload-artifact@v4
        with:
          name: android-build-${{steps.meta.outputs.project_version}}
          path: cli/build/Android
          if-no-files-found: error

      # CLI call to simulated upload process
      - name: Upload
        if: github.event_name == 'push' && github.ref_name == 'main'
        env:
          UPLOAD_TOKEN: dummy-token-credentials
        run: |
          find build/Android -type f | while read -r artifact
          do
            bash ./upload.sh android "$artifact"
          done